//===-- JavaJITOpenJDK.h - OpenJDK-specific JavaJIT Methods ---------------===//
//
//                            The VMKit project
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//

void JavaJIT::lowerArraycopy(std::vector<Value*>& args) {
  UNIMPLEMENTED();
}

