# Set the name of the project here
PROJECT_NAME := vmkit-joe
PROJ_VERSION := 0.01

# Set the directory root of this project's source files
PROJ_SRC_ROOT := $(PWD)/vmkit
VMKIT_SRC_ROOT := $(PROJ_SRC_ROOT)

# Set the root directory of this project's object files
PROJ_OBJ_ROOT := $(PWD)/vmkit
VMKIT_OBJ_ROOT := $(PROJ_OBJ_ROOT)

# Set the root directory of this project's install prefix
PROJ_INSTALL_ROOT := @prefix@

MMTK_PLAN = @MMTK_PLAN@
MMTK_PLAN_HEADER = @MMTK_PLAN_HEADER@
WITH_64 = @WITH_64@
ANT = @ANT@
ARCH:=i686

CLASSPATH_IMPL = gnuclasspath

ifeq ($(CLASSPATH_IMPL),gnuclasspath)
	CLASSPATH_DIR = GNUClasspath
else
	ifeq ($(CLASSPATH_IMPL),openjdk)
		CLASSPATH_DIR = OpenJDK
	else
$(error Unsupported classpath implementation "$(CLASSPATH_IMPL)")
	endif
endif
