##===- mmtk/magic/Makefile ---------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../..

include $(LEVEL)/Makefile.config

LIBRARYNAME = MMTKMagic
LOADABLE_MODULE = 1

include $(LEVEL)/Makefile.common

