##===- lib/Mvm/StaticGCPass/Makefile -----------------------*- Makefile -*-===##
#
#                            The VMKit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../../..

include $(LEVEL)/Makefile.config

LIBRARYNAME = StaticGCPass
LOADABLE_MODULE = 1

include $(LEVEL)/Makefile.common

