##===- tools/vmjc/libvmjc/Makefile -------------------------*- Makefile -*-===##
# 
#                     The VMKit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

include $(LEVEL)/Makefile.config

LIBRARYNAME = libvmjc
LOADABLE_MODULE = 1
VMJC_ASSEMBLY = 1
BUILT_SOURCES = glibj.zip.s

SOURCES = glibj.zip.s

include $(LEVEL)/Makefile.common
