##===- lib/Mvm/Makefile ------------------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..

include $(LEVEL)/Makefile.config

DIRS = CommonThread MMTk Runtime Compiler JITGCPass

include $(LEVEL)/Makefile.common
