##===- lib/Makefile ----------------------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ..

PARALLEL_DIRS = Mvm J3

include $(LEVEL)/Makefile.config

include $(LEVEL)/Makefile.common

