#!/bin/sh

qemu-system-x86_64 -m 256m -no-reboot -kernel jam.out -nographic  -device i82559c,netdev=net1 -netdev user,id=net1 -no-shutdown -d in_asm,int,exec,pcall,cpu_reset,unimp,guest_errors -D log
