##===- mmtk/Makefile ---------------------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ..

DIRS = magic mmtk-j3 mmtk-alloc java inline

include $(LEVEL)/Makefile.config

include $(LEVEL)/Makefile.common

