##===- lib/JnJVM/Makefile ----------------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..

DIRS = LLVMRuntime VMCore ClassLib Compiler

include $(LEVEL)/Makefile.config
include $(LEVEL)/Makefile.common

