##===- mmtk/java/Makefile ----------------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..

include $(LEVEL)/Makefile.config

RUN_ANT = 1
JARNAME = mmtk-vmkit
EXTRA_DIST = vmkit.properties build.xml.in src

include $(LEVEL)/Makefile.common
